### ISSUE TITLE
Unable to find coinbase order with store id

### ISSUE THREAD

**Issue by rajesh-magento** [coinbase/coinbase-commerce-magento#11]
I'm not able to view order details from Admin panel,
1 exception(s):
Exception #0 (Magento\Framework\Exception\NoSuchEntityException): Unable to find coinbase order with store id "000000128"

Exception #0 (Magento\Framework\Exception\NoSuchEntityException): Unable to find coinbase order with store id "000000128"
#0 /var/www/html/qa_v2/aroma2gom2/app/code/CoinbaseCommerce/PaymentGateway/Block/Adminhtml/Order/View/Details.php(36): CoinbaseCommerce\PaymentGateway\Model\CoinbaseRepository->getByIncrementId('000000128')
#1 /var/www/html/qa_v2/aroma2gom2/app/code/CoinbaseCommerce/PaymentGateway/Block/Adminhtml/Order/View/Details.php(46): CoinbaseCommerce\PaymentGateway\Block\Adminhtml\Order\View\Details->getCoinbaseRecord()
#2 /var/www/html/qa_v2/aroma2gom2/app/code/CoinbaseCommerce/PaymentGateway/view/adminhtml/templates/details.phtml(4): CoinbaseCommerce\PaymentGateway\Block\Adminhtml\Order\View\Details->getCoinsDetail()

**Comment by rajesh-magento** [comment]
Still I'm having this same issue. magento2.3.2 with php7.2

**Comment by perfpcs** [comment]
We solved it. Try:

/vendor/coinbase/coinbase-commerce-magento/Block/Adminhtml/Order/View/Details.php

lines: 44 ~ 63

    public function getCoinsDetail()
    {
        try {
            $record = $this->getCoinbaseRecord();
            $data['expectedCoins'] = $record->getCoinsExpected() . ' ' . $record->getReceivedCurrency();
            $data['amount'] = $record->getCoinsReceived() . ' ' . $record->getReceivedCurrency();
            $data['status'] = $record->getCoinbaseStatus();
            $data['code'] = $record->getCoinbaseChargeCode();
            $data['transactionId'] = $record->getTransactionId();
            $data['totalPaid'] = $record->getTotalPaid();
            $data['orderPlacedCurrency'] = $this->getOrder()->getOrderCurrencyCode();
        } catch (\Exception $e) {
            $data['expectedCoins'] = '';
            $data['amount'] = '';
            $data['status'] = '';
            $data['code'] = '';
            $data['transactionId'] = '';
            $data['totalPaid'] = '';
            $data['orderPlacedCurrency'] = '';
        }

**Comment by oa-coinbase** [comment]
Hi folks, unfortunately we are moving towards deprecating support for the Magento plugin as it hasn't captured enough audience for us to maintain it at this time. However, we may come back to it in the future. The php SDK however will be kept alive. Feel free to clone this repository to make modifications for your use, which it seems by now you may have, or post any PR's you would like to fix for the php SDK to share with the community. Sorry we couldn't be more helpful at this time.
