### ISSUE TITLE
Multiple Issues with this extension in M 2.3.3

### ISSUE THREAD

**Issue by perfpcs** [coinbase/coinbase-commerce-magento#12]
This extension has many issues preventing it from working correctly in the latest Magento 2.3.3

1. As soon as you click submit to make the order and pay via coinbase commerce, an order is created immediately, even before doing anything else. If you click Cancel and return to store the item is still in the cart but the order is already made.

2. If you pay the order properly and click the link to return to store, or let it timeout to go back automatically: you go to empty cart page instead of checkout/success (thank you page) and it says: 
with this URL:
https://test.performance-pcs.com/coinbasecommerce/webhook/redirect/
"Sorry something went wrong, you will be redirected to checkout in 5 seconds."

3. The link for the link "Learn More" adds our website to the URL and so it goes to invalid page. Instead of https://commerce.coinbase.com it goes to: https://xxxxxxxxx.com/checkout/%E2%80%9Chttps://commerce.coinbase.com/%E2%80%9D

How can anyone even be using this extension with so many bugs?? I mean it looks nice and works well overall but there is no way to use this on a live site just for the first 2 bugs alone. Can anyone help here?? I'd even pay a small fee to fix the code for these few bugs..I'm sure the 3rd one is easy.

**Comment by perfpcs** [comment]
So no one replies here or wants to fix this mess of an extension??

**Comment by perfpcs** [comment]
Why is this group so useless?? 5v Contributors to the extension and not one person can reply to anyone and fix the problems. In latest M 2.3.4 and php 7.3 add to the list of problems (and this is worst problems). "Unable to find Coinbase order with store id". As posted here by at least 5-6 others.
Why is there no support from Coinbase Commerce?? They don't reply to emails and no one here seems to give a damn about fixing all these problems with this extension. In it's current state the extension is useless since you cannot view any order made paid with Coinbase Commerce, Extension just breaks backend. Is anyone able to fix this issue, even for pay?????

**Comment by perfpcs** [comment]
So with the help with one of our developers we fixed the main problem of not being able to view Coinbase orders in the Admin order grid.

1 exception(s):
Exception #0 (Magento\Framework\Exception\NoSuchEntityException): Unable to find coinbase order with store id "ORD-200325-4-009"

Exception #0 (Magento\Framework\Exception\NoSuchEntityException): Unable to find coinbase order with store id "ORD-200325-4-009"
<pre>#1 CoinbaseCommerce\PaymentGateway\Block\Adminhtml\Order\View\Details->getCoinbaseRecord() called at [vendor/coinbase/coinbase-commerce-magento/Block/Adminhtml/Order/View/Details.php:46]
#2 CoinbaseCommerce\PaymentGateway\Block\Adminhtml\Order\View\Details->getCoinsDetail() called at [vendor/coinbase/coinbase-commerce-magento/view/adminhtml/templates/details.phtml:4]
#3 include() called at [vendor/magento/framework/View/TemplateEngine/Php.php:59]

Solution:

/vendor/coinbase/coinbase-commerce-magento/Block/Adminhtml/Order/View/Details.php

lines: 44 ~ 63

    public function getCoinsDetail()
    {
        try {
            $record = $this->getCoinbaseRecord();
            $data['expectedCoins'] = $record->getCoinsExpected() . ' ' . $record->getReceivedCurrency();
            $data['amount'] = $record->getCoinsReceived() . ' ' . $record->getReceivedCurrency();
            $data['status'] = $record->getCoinbaseStatus();
            $data['code'] = $record->getCoinbaseChargeCode();
            $data['transactionId'] = $record->getTransactionId();
            $data['totalPaid'] = $record->getTotalPaid();
            $data['orderPlacedCurrency'] = $this->getOrder()->getOrderCurrencyCode();
        } catch (\Exception $e) {
            $data['expectedCoins'] = '';
            $data['amount'] = '';
            $data['status'] = '';
            $data['code'] = '';
            $data['transactionId'] = '';
            $data['totalPaid'] = '';
            $data['orderPlacedCurrency'] = '';
        }
There is still numerous issues with this extension listed above but no one here or from Coinbase support helps or replies in any manner nor do they seem interested to fix this extension.

**Comment by oa-coinbase** [comment]
Hi @perfpcs unfortunately we are moving towards deprecating support for the Magento plugin as it hasn't captured enough audience for us to maintain it at this time. However, we may come back to it in the future. The php SDK however will be kept alive. Feel free to clone this repository to make modifications for your use, which it seems by now you may have, or post any PR's you would like to fix for the php SDK to share with the community. Sorry we couldn't be more helpful at this time.
