### ISSUE TITLE
Exception #0 (Magento\Framework\Exception\NoSuchEntityException): Unable to find coinbase order with store id "000000230"

### ISSUE THREAD

**Issue by rselvakumarnits** [coinbase/coinbase-commerce-magento#14]
Exception #0 (Magento\Framework\Exception\NoSuchEntityException): Unable to find coinbase order with store id "000000230"
<pre>#1 CoinbaseCommerce\PaymentGateway\Block\Adminhtml\Order\View\Details->getCoinbaseRecord() called at [app/code/CoinbaseCommerce/PaymentGateway/Block/Adminhtml/Order/View/Details.php:46]

Above issue happen because while place order data not storing to table "coinbase_commerce_orders"

**Comment by perfpcs** [comment]
We solved. Try this:

/vendor/coinbase/coinbase-commerce-magento/Block/Adminhtml/Order/View/Details.php

lines: 44 ~ 63 add:

    public function getCoinsDetail()
    {
        try {
            $record = $this->getCoinbaseRecord();
            $data['expectedCoins'] = $record->getCoinsExpected() . ' ' . $record->getReceivedCurrency();
            $data['amount'] = $record->getCoinsReceived() . ' ' . $record->getReceivedCurrency();
            $data['status'] = $record->getCoinbaseStatus();
            $data['code'] = $record->getCoinbaseChargeCode();
            $data['transactionId'] = $record->getTransactionId();
            $data['totalPaid'] = $record->getTotalPaid();
            $data['orderPlacedCurrency'] = $this->getOrder()->getOrderCurrencyCode();
        } catch (\Exception $e) {
            $data['expectedCoins'] = '';
            $data['amount'] = '';
            $data['status'] = '';
            $data['code'] = '';
            $data['transactionId'] = '';
            $data['totalPaid'] = '';
            $data['orderPlacedCurrency'] = '';
        }

**Comment by oa-coinbase** [comment]
Hi folks, unfortunately we are moving towards deprecating support for the Magento plugin as it hasn't captured enough audience for us to maintain it at this time. However, we may come back to it in the future. The php SDK however will be kept alive. Feel free to clone this repository to make modifications for your use, which it seems by now you may have, or post any PR's you would like to fix for the php SDK to share with the community. Sorry we couldn't be more helpful at this time.
