### ISSUE TITLE
Payment Method not Appears

### ISSUE THREAD

**Issue by RidasRyan** [coinbase/coinbase-commerce-magento#2]
Hello sir,

I really appreciate your module. I try to use Coinbase commerce to our payment method but after install =>http://prntscr.com/lc44xr

and configure as you ask => http://prntscr.com/lc468o, I don't see the payment option in my site => http://prntscr.com/lc448p

Can you please help me?

**Comment by RidasRyan** [comment]
can you help me to get tutorial or can I hire you?

**Comment by RidasRyan** [comment]
@guacamoli do you think where is the issue of it?? because our team said that is issue from coinbase module. do you have email sir?

**Comment by RidasRyan** [comment]
@guacamoli @maksim-s @adam-olsen-coinbase hello sir, any update? We really need this payment

**Comment by chalk777** [comment]
@RidasRyan Could you please provide magento's version of your store. I'll try to install on my side and test.

**Comment by RidasRyan** [comment]
Magento 2 V 2.2
rgrds,
Ryan 

   Pada Senin, 5 November 2018 00.13.58 GMT+7, Igor <notifications@github.com> menulis: 
 
 
@RidasRyan Could you please provide magento's version of your store. I'll try to install on my side and test.

**Comment by RidasRyan** [comment]
We really need this module sir. can you help us?? please...
rgrds,
Ryan 

   Pada Senin, 5 November 2018 00.13.58 GMT+7, Igor <notifications@github.com> menulis: 
 
 
@RidasRyan Could you please provide magento's version of your store. I'll try to install on my side and test.

**Comment by chalk777** [comment]
@RidasRyan ![image](https://user-images.githubusercontent.com/1286265/48136609-c4dcfc00-e2a8-11e8-9cc1-d7c654e21546.png)
Unfortunately can't replicate on my side. Tested with installed magento v2.2.2.

**Comment by RidasRyan** [comment]
Can you check on my side sir..please

Warm regards,
Ryan 
 
  Pada Rab, 7 Nov 2018 pada 21:21, Igor Meleshko<notifications@github.com> menulis:   
@RidasRyan 
Unfortunately can't replicate on my side. Tested with installed magento v2.2.2.

**Comment by guacamoli** [comment]
Hi @RidasRyan, we’ve recently updated the package and confirmed that it works with the version you are using. Please download the latest package and try it again. We can’t offer any additional support at the moment.

**Comment by RidasRyan** [comment]
we have downloaded again and installed again but still not appears when check out 




rgrds,
Ryan 

   Pada Rabu, 7 November 2018 23.11.20 GMT+7, Sahil Amoli <notifications@github.com> menulis: 
 
 
Hi @RidasRyan, we’ve recently updated the package and confirmed that it works with the version you are using. Please download the latest package and try it again. We can’t offer any additional support at the moment.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or mute the thread.
   

|  | Virus-free. www.avast.com  |

**Comment by RidasRyan** [comment]
may i know your url to check it?? our developer will check the code from your test site
rgrds,
Ryan 

   Pada Rabu, 7 November 2018 23.11.20 GMT+7, Sahil Amoli <notifications@github.com> menulis: 
 
 
Hi @RidasRyan, we’ve recently updated the package and confirmed that it works with the version you are using. Please download the latest package and try it again. We can’t offer any additional support at the moment.

**Comment by RidasRyan** [comment]
Hello sir,
I had paid and hired two developers. but all of them still don't find the issue. they said only you can check the issue.
We try to make your company famous for our customers. we have new customers every day and ready to register in your company but why your support is not good sir???
please your support.


rgrds,
Ryan 

   Pada Rabu, 7 November 2018 23.11.20 GMT+7, Sahil Amoli <notifications@github.com> menulis: 
 
 
Hi @RidasRyan, we’ve recently updated the package and confirmed that it works with the version you are using. Please download the latest package and try it again. We can’t offer any additional support at the moment.
