### ISSUE TITLE
still doesnt appears

### ISSUE THREAD

**Issue by RidasRyan** [coinbase/coinbase-commerce-magento#4]
Hello sir,

I had paid and hired two developers. but all of them still don't find the issue. they said only you can check the issue.
We try to make your company famous for our customers. we have new customers every day and ready to register in your company but why your support is not good sir???

please your support.!!

**Comment by guacamoli** [comment]
Sorry, we've tested this on our end with your version and it works fine for us. Unfortunately, we cannot provide any more support ATM. We'll try to release some sandboxed test environments soon.
