### ISSUE TITLE
checkout button does not show for magento 2.3

### ISSUE THREAD

**Issue by erobotics** [coinbase/coinbase-commerce-magento#8]
will you be able to debug it? thanks.

**Comment by oa-coinbase** [comment]
Hi @erobotics, unfortunately we are moving towards deprecating support for the Magento plugin as it hasn't captured enough audience for us to maintain it at this time. However, we may come back to it in the future. The php SDK however will be kept alive. Feel free to clone this repository to make modifications for your use, which it seems by now you may have, or post any PR's you would like to fix for the php SDK to share with the community. Sorry we couldn't be more helpful at this time.
