### ISSUE TITLE
error in view the order in magento 2.3.0

### ISSUE THREAD

**Issue by YasserNasser** [coinbase/coinbase-commerce-magento#9]
when i make an order and not complete the payment then i go to the magento dashboard to see the order
click in view order i get this exception
1 exception(s):
Exception #0 (Magento\Framework\Exception\NoSuchEntityException): Unable to find coinbase order with store id "2000000006"

Exception #0 (Magento\Framework\Exception\NoSuchEntityException): Unable to find coinbase order with store id "2000000006"
#0 /home/.www/shJnco/public/app/code/CoinbaseCommerce/PaymentGateway/Block/Adminhtml/Order/View/Details.php(36): CoinbaseCommerce\PaymentGateway\Model\CoinbaseRepository->getByIncrementId('2000000006')
#1 /home/.www/shJnco/public/app/code/CoinbaseCommerce/PaymentGateway/Block/Adminhtml/Order/View/Details.php(46): CoinbaseCommerce\PaymentGateway\Block\Adminhtml\Order\View\Details->getCoinbaseRecord()
#2 /home/.www/shJnco/public/app/code/CoinbaseCommerce/PaymentGateway/view/adminhtml/templates/details.phtml(4): CoinbaseCommerce\PaymentGateway\Block\Adminhtml\Order\View\Details->getCoinsDetail()
#3 /home/.www/shJnco/public/vendor/magento/framework/View/TemplateEngine/Php.php(59): include('/home/.www/shJn...')
#4 /home/.www/shJnco/public/vendor/magento/framework/View/Element/Template.php(271): Magento\Framework\View\TemplateEngine\Php->render(Object(CoinbaseCommerce\PaymentGateway\Block\Adminhtml\Order\View\Details), '/home/.www/shJn...', Array)

**Comment by rajesh-magento** [comment]
I have this same issue. Are you find got any solution

**Comment by riccardofinkers** [comment]
Same issue here .... not compatible with 2.3.x I'm running on 2.3.3 in combination with PHP 7.2

**Comment by alrururu** [comment]
same issue on M2 2.3.3 php 7.3

**Comment by rajesh-magento** [comment]
I have this same issue. Have you any solution?

**Comment by perfpcs** [comment]
Same issue using 2.3.4 and php 7.3. Is anyone working on any of these problems??

**Comment by perfpcs** [comment]
We solved it. Try:

/vendor/coinbase/coinbase-commerce-magento/Block/Adminhtml/Order/View/Details.php

lines: 44 ~ 63

    public function getCoinsDetail()
    {
        try {
            $record = $this->getCoinbaseRecord();
            $data['expectedCoins'] = $record->getCoinsExpected() . ' ' . $record->getReceivedCurrency();
            $data['amount'] = $record->getCoinsReceived() . ' ' . $record->getReceivedCurrency();
            $data['status'] = $record->getCoinbaseStatus();
            $data['code'] = $record->getCoinbaseChargeCode();
            $data['transactionId'] = $record->getTransactionId();
            $data['totalPaid'] = $record->getTotalPaid();
            $data['orderPlacedCurrency'] = $this->getOrder()->getOrderCurrencyCode();
        } catch (\Exception $e) {
            $data['expectedCoins'] = '';
            $data['amount'] = '';
            $data['status'] = '';
            $data['code'] = '';
            $data['transactionId'] = '';
            $data['totalPaid'] = '';
            $data['orderPlacedCurrency'] = '';
        }

**Comment by oa-coinbase** [comment]
Hi folks, unfortunately we are moving towards deprecating support for the Magento plugin as it hasn't captured enough audience for us to maintain it at this time. However, we may come back to it in the future. The php SDK however will be kept alive. Feel free to clone this repository to make modifications for your use, which it seems by now you may have, or post any PR's you would like to fix for the php SDK to share with the community. Sorry we couldn't be more helpful at this time.
